#! /bin/sh

# 快捷键配置
sxhkd &
# 输入法
fcitx5 &
# 混成器
picom -b &
# 随机壁纸
bash /home/mxlei/.local/bin/shell/random-background.sh &
# 消息通知
dunst &
# utools
utools &
# 邮箱
mailspring &
# 钉钉
dingtalk &
# 微信
# wine "/home/mxlei/.wine/drive_c/Program Files (x85)/Tencent/WeChat/WeChat.exe" &

# bspwm配置项
bspc config border_width         0
bspc config window_gap           5
bspc config normal_border_color  \#0000
bspc config focused_border_color \#ffb300
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# 多显示器 
monitorCount=`xrandr --listmonitors | wc -l`
if [ $monitorCount -gt 2 ]; 
  then
    xrandr --output HDMI-0 --primary --mode 1920x1080 --rate 60.00
    xrandr --output DVI-D-0 --right-of HDMI-0
    # xrandr --output DVI-D-0 --off
    bspc monitor HDMI-0 -n center
    bspc monitor DVI-D-0 -n right
    bspc monitor center -d 1 2 3 4 5
    # bspc monitor right -d 4 5 6
  else
    bspc monitor -d 1 2 3 4 5
fi
# 状态栏
bash ~/.config/polybar/launch.sh --material

# 特定程序窗口的设置
# 可以命令查看窗口的名称 xprop | grep WM_CLASS 后点击窗口即可
# bspc rule -a vlc state=floating
bspc rule -a Sxiv state=floating
bspc rule -a feh state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a tim.exe state=tiled desktop='^3'
bspc rule -a wechat state=tiled desktop=^3
bspc rule -a com.alibabainc.dingtalk state=floating
bspc rule -a jetbrains-studio desktop='^2'
bspc rule -a mailspring desktop='^4'
bspc rule -a Mailspring desktop='^4'
bspc rule -a netease-cloud-music state=floating
# 计算器
bspc rule -a gnome-calculator state=floating
# 日历
bspc rule -a Gnome-calendar state=floating
# 百度网盘
bspc rule -a baidunetdisk state=floating
bspc rule -a utools state=floating
bspc rule -a Utools state=floating
