#! /bin/bash

# 自动启动
autoStart() {
  # 快捷键配置
  sxhkd &
  # 输入法
  fcitx5 &
  # 混成器
  picom -b --experimental-backends &
  # 随机壁纸
  feh --bg-fill --randomize --recursive /home/mxlei/Pictures/bing_wallpapers/ &
  # 消息通知
  dunst &
  # utools
  utools &
  # 邮箱
  # mailspring --password-store="gnome-libsecret" &
  # 钉钉
  # dingtalk &
  # 微信
  # wine "/home/mxlei/.wine/drive_c/Program Files (x85)/Tencent/WeChat/WeChat.exe" &
  # 图床工具
  /home/mxlei/bin/PicGo-2.4.0.AppImage &
  # 蓝牙
  blueman-applet &
  # 剪贴板管理
  copyq &
}

# 针对不同的电脑环境进行配置，如多显示器
configForEnvironment() {
  config_success=0
  java -version
  cpu=$(grep "model name" /proc/cpuinfo | cut -d ':' -f 2 | awk 'NR==1{print $0}')
  # 家里电脑
  if [ "$cpu" = " AMD Ryzen 7 3700X" ];
    then
      config_success=1
      mainMonitor="HDMI-0"
      subMonitor="DVI-D-0"
      xrandr --output $mainMonitor --primary --mode 1920x1080 
      xrandr --output $subMonitor --right-of $mainMonitor
      bspc monitor $mainMonitor -n center
      bspc monitor center -d 1 2 3 4 5
  fi
  # 公司电脑
  if [ "$cpu" = " 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz" ];
    then
      config_success=1
      mainMonitor="HDMI-2"
      subMonitor="DP-2"
      xrandr --output $mainMonitor --primary --mode 2560x1440 
      xrandr --output $subMonitor --left-of $mainMonitor
      bspc monitor $mainMonitor -n center
      bspc monitor center -d 1 2 3 4 5
  fi
  # 笔记本
  if [ "$cpu" = " AMD Ryzen 7 6800H with Radeon Graphics" ];
    then
      echo "deviceType: 6800H"
      config_success=1
      mainMonitor="HDMI-A-0"
      subMonitor="eDP"
      if [ "$(xrandr --listmonitors | wc -l)" -gt 2  ]; then
        xrandr --output $subMonitor --brightness 0.6
        xrandr --output $mainMonitor --above $subMonitor --primary 
        (sleep 2; xrandr --output $subMonitor --mode 1920x1200) &
      else 
        mainMonitor=$subMonitor
        xrandr --output $mainMonitor --primary  --brightness 0.6
      fi
      bspc monitor $mainMonitor -n center
      bspc monitor center -d 1 2 3 4 5
  fi
  # 无界14x
  if [ "$cpu" = " AMD Ryzen 7 8845HS w/ Radeon 780M Graphics" ]; then
    # 屏幕亮度
    # brightness_file="/sys/class/backlight/amdgpu_bl1/brightness"
    # if [ -f $brightness_file ]; then
    #   echo 100 >$brightness_file
    # fi
    config_success=1
-   mainMonitor="HDMI-A-0"
-   subMonitor="eDP"
-   subMonitor2="DisplayPort-0"
    xrandr --output $mainMonitor --mode 2560x1440
    xrandr --output $subMonitor2 --mode 2560x1440
    xrandr --output $subMonitor --mode 1920x1200
    if [ "$(xrandr | grep ' connected ' | wc -l)" -eq 3  ]; then
      xrandr --output $mainMonitor --primary 
      xrandr --output $subMonitor --below $mainMonitor --brightness 0.6
      xrandr --output $subMonitor2 --left-of $mainMonitor
      #(sleep 2; xrandr --output $subMonitor --mode 1920x1200) &
    elif [ "$(xrandr | grep ' connected ' | wc -l)" -eq 2  ]; then 
      xrandr --output $mainMonitor --primary 
      xrandr --output $subMonitor --below $mainMonitor --brightness 0.6
      #(sleep 2; xrandr --output $subMonitor --mode 1920x1200) &
    else 
      mainMonitor=$subMonitor
    xrandr --output $subMonitor --mode 1920x1200
      xrandr --output $mainMonitor --primary --brightness 0.6
    fi
    bspc monitor $mainMonitor -n center
    bspc monitor center -d 1 2 3 4 5
  fi
  # 拯救者r9000p
  if [ "$cpu" = " AMD Ryzen 9 7945HX with Radeon Graphics" ]; then
    # 屏幕亮度
    # brightness_file="/sys/class/backlight/amdgpu_bl1/brightness"
    # if [ -f $brightness_file ]; then
    #   echo 100 >$brightness_file
    # fi
    config_success=1
    mainMonitor="HDMI-0"
    subMonitor="DP-4"
    subMonitor2="DP-3"
    xrandr --output $mainMonitor --mode 2560x1440
    xrandr --output $subMonitor2 --mode 2560x1440
    xrandr --output $subMonitor --mode 1920x1200
    if [ "$(xrandr | grep ' connected ' | wc -l)" -eq 3  ]; then
      xrandr --output $mainMonitor --primary 
      xrandr --output $subMonitor --below $mainMonitor --brightness 0.6
      xrandr --output $subMonitor2 --left-of $mainMonitor
      #(sleep 2; xrandr --output $subMonitor --mode 1920x1200) &
    elif [ "$(xrandr | grep ' connected ' | wc -l)" -eq 2  ]; then 
      xrandr --output $mainMonitor --primary 
      xrandr --output $subMonitor --below $mainMonitor --brightness 0.6
      #(sleep 2; xrandr --output $subMonitor --mode 1920x1200) &
    else 
      mainMonitor=$subMonitor
    xrandr --output $subMonitor --mode 1920x1200
      xrandr --output $mainMonitor --primary --brightness 0.6
    fi
    bspc monitor $mainMonitor -n center
    bspc monitor center -d 1 2 3 4 5
  fi
  # bspc monitor $subMonitor -n right
  # bspc monitor right -d 4 5 6
  # xrandr --output DVI-D-0 --off
  # 未识别的电脑默认配置
  if [ $config_success -eq 0 ];
    then
      mainMonitor=`xrandr --listmonitors | awk 'NR==2{print $4}'`
      xrandr --output $mainMonitor --mode 1920*1080
      bspc monitor -d 1 2 3 4 5
  fi
}

# bspwm配置项
configBspwm() {
  bspc config border_width         0
  bspc config window_gap           5
  bspc config normal_border_color  \#0000
  bspc config focused_border_color \#ffb300
  bspc config split_ratio          0.52
  bspc config borderless_monocle   true
  bspc config gapless_monocle      true
  # 特定程序窗口的设置
  # 可以命令查看窗口的名称 xprop | grep WM_CLASS 后点击窗口即可
  # bspc rule -a vlc state=floating
  bspc rule -a Sxiv state=floating
  bspc rule -a feh state=floating
  bspc rule -a mplayer2 state=floating
  bspc rule -a Kupfer.py focus=on
  bspc rule -a Screenkey manage=off
  bspc rule -a Gimp desktop='^5' state=floating follow=on
  bspc rule -a tim.exe state=tiled desktop='^3'
  #bspc rule -a wechat state=tiled desktop=^3
  bspc rule -a com.alibabainc.dingtalk state=floating
  # bspc rule -a jetbrains-studio desktop='^3'
  bspc rule -a mailspring desktop='^4'
  bspc rule -a Mailspring desktop='^4'
  # 音乐
  bspc rule -a netease-cloud-music state=floating
  bspc rule -a listen1 state=floating
  bspc rule -a qqmusic state=floating
  # 计算器
  bspc rule -a gnome-calculator state=floating
  bspc rule -a cutefish-calculator state=floating
  # 日历
  bspc rule -a Gnome-calendar state=floating
  # 百度网盘
  bspc rule -a baidunetdisk state=floating
  bspc rule -a utools state=floating
  bspc rule -a Utools state=floating
  # 飞书投屏
  bspc rule -a Metting state=floating
  # qv2ray代理
  bspc rule -a qv2ray state=floating
  # 提示框
  bspc rule -a zenity state=floating
  # 蓝牙管理
  bspc rule -a blueman-manager state=floating
  # copyq剪贴板
  bspc rule -a copyq state=floating
}

daka_notify() {
  now_hour=$(date +%H)
  if [[ 
      ($now_hour -gt 7 && $now_hour -lt 10) || 
      ($now_hour -gt 20 && $now_hour -lt 24)
    ]]; then
    zenity --info --text "记得打卡"
  fi
}

configForEnvironment
configBspwm
sleep 1
autoStart
# 状态栏
sleep 3
bash ~/.config/polybar/launch.sh --material

